### ISSUE TITLE
No status for some repositories

### ISSUE THREAD

**Issue by xfzv** [llanosrocas/githead.yazi#1]
I have some Git repositories cloned locally that were present on my disk prior to starting using `githead.yazi`. For some of them, there is no Git status at all (I assume at least the branch part should be displayed):

- Works:
![image](https://github.com/user-attachments/assets/f75bb744-ae44-47ae-90d2-89bb56b25019)

- Doesn't work:
![image](https://github.com/user-attachments/assets/1aefade2-c91e-43fc-bc97-9aea6f0f2fdc)
![image](https://github.com/user-attachments/assets/bb7d38f7-3f8c-4e95-bc29-8d1e44cbcf0c)
![image](https://github.com/user-attachments/assets/853a7db9-35ad-4996-a66f-bae33149cb53)

Interestingly, cloning the repositories again fixes the issue:

```console
% git clone https://github.com/hrsh7th/cmp-nvim-lsp.git /tmp/cmp-nvim-lsp
% git clone https://github.com/stevearc/conform.nvim.git /tmp/conform.nvim
% git clone https://github.com/sindrets/diffview.nvim.git /tmp/diffview.nvim
```

![image](https://github.com/user-attachments/assets/ee1502dd-f365-49dc-8c98-4f6e41218c1b)
![image](https://github.com/user-attachments/assets/2ef7c757-c0d2-4500-8647-9f07819fc65e)
![image](https://github.com/user-attachments/assets/58f3406b-dc3b-4bdd-8e84-fa89eaca5e7d)

Additional details:

```console
% uname -s
Linux

% yazi -V
Yazi 0.2.5 (66e83f3 2024-07-21)

% git --version
git version 2.44.2
```

- `~/.config/yazi/init.lua`

```lua
require("githead"):setup({})
```

**Comment by llanosrocas** [comment]
1) Can you show me the output of this command `git status --ignore-submodules=dirty --branch` in your old repo?
2) And what version/commit of the plugin are you using? I just pushed some changes, so you might want to try it while I look for the problem.

**Comment by llanosrocas** [comment]
Thank you.
Seems like I need to implement logic for detached HEAD state.

**Comment by llanosrocas** [comment]
Please try 4683eec. It should show you the commit like so:
<img width="431" alt="Screenshot 2024-07-23 at 15 01 51" src="https://github.com/user-attachments/assets/ac4e1e24-a6c8-4a75-a142-d50069b2402b">
