### ISSUE TITLE
feat: Yatline Support

### ISSUE THREAD

**Issue by imsi32** [llanosrocas/githead.yazi#4]
Hi, with [yatline.yazi](https://github.com/imsi32/yatline.yazi)'s v0.3.0 support. I implemented an add-on system and I was planning to
make a git add-on but I saw your plugin and decided to ask you if I can add a support for yatline.

If you approve it, I write the implementation already so I can open a pull request right away.

Moreover, githead still be usable even if yatline is not plugged.

**Comment by llanosrocas** [comment]
Yes, go ahead, you can use it. I'll approve the PR's.
