### ISSUE TITLE
Is it fast in linux? `io.popen()` make yazi slow in window 

### ISSUE THREAD

**Issue by Jaehaks** [llanosrocas/githead.yazi#6]
Thank you for your efforts, 

I am modifying your plugin to use this plugin in windows. 
io.popen makes delay in windows so It makes many input lag, how about in linux?

**Comment by TicTak21** [comment]
Hello,
I'm using macos, and I am not experiencing any lag. 
1. Could you explain how you measured the `io.popen` delay?
2. I suspect the issue might be related to parsing the output of git status. Could you share your git status output?

**Comment by llanosrocas** [comment]
Hello.
I'm using macos, and I am not experiencing any lag. 1. Could you explain how you measured `io.popen` delay?
2. I suspect the issue might be related to parsing the output of git status. Could you share output of the following command: `git status --ignore-submodules=dirty --branch --show-stash --ahead-behind`?

**Comment by Jaehaks** [comment]
@llanosrocas 

the response of git status isn't problem as I think.


https://github.com/user-attachments/assets/504e5627-abc1-4b9e-ba43-22354833ff50

https://github.com/user-attachments/assets/7721f984-fec6-42a8-85af-acc89fe71874


The output of `git status ~` which you said
```
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   windows-terminal/settings/settings.json
        modified:   windows-terminal/settings/state.json
        modified:   yazi/init.lua

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        yazi/plugins/githead.yazi/

no changes added to commit (use "git add" and/or "git commit -a")
Your stash currently has 3 entries
```

**Comment by llanosrocas** [comment]
Alright. As far as I understand, you've modified the source code. If so, please share it, as I can't guarantee your modifications are free of bugs.
I'll try to install yazi on Windows and maybe I can help you.

**Comment by Jaehaks** [comment]
@llanosrocas 

After searching, it seems `io.popen` is much slower  in Windows than linux. 

The difference of command is only  replacing `2>/dev/null` with `2>null` in Windows. 
and `Command()` doesn't work well if it executes in `Header:githead()`

I'am newbie in yazi and lua. so I'm not sure when it will be finished. but I'll try it

**Comment by Jaehaks** [comment]
I think it works, with inspired by your code and [git.yazi](https://github.com/yazi-rs/plugins/blob/main/git.yazi/init.lua)
What a nice timing!!

1) if `git status` uses `2>nul` in `Command()` for Windows, commit / unstaged / staged message cannot be shown properly. but it works well in terminal. it's weird
2) It calls `git status` multiple times( 2~3 typical) whenever entering directories. 
   I don't like this way, but it is only way what I know.... 
   it can use `Command()` and don't make any input delay.
3) `ya.render()` is very important to reset `ui.Line`

> githead.yazi/init.lua
```lua
-- get branch contents from status
local get_branch = ya.sync(function (state, status)
  local branch = status:match('On branch (%S+)')
  state.branch = branch and '  ' .. branch or ""
end)

-- get stash contents from status
local get_stash = ya.sync(function (state, status)
  local stash = status:match('Your stash currently has (%S+)')
  state.stash = stash and ' $' .. stash or ""
end)

-- get commit contents from status
local get_commit = ya.sync(function (state, status)
  local commit = status:match('onto (%S+)')
  state.commit = commit and ' @' .. commit or ""
end)

-- setup function to register Header
local setup = function(state, args)
  state.branch = ''
  state.stash = ''
  state.staged = ''
  state.unstaged = ''
  state.commit = ''
  state.untracked = ''
  
  -- githead main function
  function Header:githead()
    ya.render() -- it needs to erase branch fast out of git repo
    
    return ui.Line{ -- must not be nil, it branch is nil, header isn't shown
      ui.Span(state.branch):fg('bright magenta'),
      ui.Span(state.stash):fg('bright blue'),
      ui.Span(state.staged):fg('bright green'),
      ui.Span(state.unstaged):fg('red'),
      ui.Span(state.commit):fg('bright yellow'),
      ui.Span(state.untracked):fg('gray'),
    }
  end
  
  -- register githead() to Header process
  Header:children_add(Header.githead, 3000, Header.LEFT)
end


local fetch = function (self)
  local cwd = self.files[1].url:parent() -- get cwd
  local status, err = Command('git')
                  :cwd(tostring(cwd))
                  :args({'--no-optional-locks', '-c', 'core.quotePath='})
                  :args({'status'})
                  :args({'--ignore-submodules=dirty', '--branch', '--show-stash', '--ahead-behind'})
                  :stdout(Command.PIPED)
                  :output()
  if not status then
    status.stdout = ""
  end
  
  -- save branch name
  get_branch(status.stdout)
  get_stash(status.stdout)
  get_staged(status.stdout)
  get_unstaged(status.stdout)
  get_commit(status.stdout)
  get_untracked(status.stdout)
  return 3

end


return {setup = setup, fetch = fetch}

```

> yazi.toml
```toml
[plugin]
fetchers = [
 { id = 'githead', name='*', run = 'githead'},
 { id = 'githead', name='*/', run = 'githead'}
]

```

If you think it is more nice idea, you can use it.
Windows is more slower than linux in this inspect.

**Comment by llanosrocas** [comment]
I'm glad you managed to get it to work.
